PassHolder/Entities/Group.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PassHolder.Entities
{
    public class Group
    {
        public int Id { get; set; }
        public string Name { get; set; }

        public virtual IEnumerable<GroupsToPass> GroupsToPasses { get; set; }
        public virtual IEnumerable<GroupToUser> GroupsToUsers { get; set; }
    }
}

PassHolder/Entities/PassData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PassHolder.Entities
{
    public class PassData
    {
        public int Id { get; set; }
        public int AppUserId { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual IEnumerable<GroupsToPass> GroupsToPasses { get; set; }
    }
}

PassHolder/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using AutoMapper;
using PassHolder.Commands;
using PassHolder.Entities;
using PassHolder.Models;
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PassHolder.Queries;

namespace PassHolder.Controllers
{
    public class GroupController : Controller
    {
        private UserManager<AppUser> _userManager;
        private SignInManager<AppUser> _singInManager;
        private RoleManager<AppRole> _roleManager;
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;

        public GroupController(UserManager<AppUser> userManager, 
           SignInManager<AppUser> singInManager,
           RoleManager<AppRole> roleManager,
           IMapper mapper,
           IMediator mediator)
        {
            _userManager = userManager;
            _singInManager = singInManager;
            _roleManager = roleManager;
            _mapper = mapper;
            _mediator = mediator;
        }


        public async Task<IActionResult> GroupsLoad()
        {

            ViewBag.Title = "Groups";
            var groups = await _mediator.Send(new AllGroupQuery());


            return View("Groups", groups);
        }


        

    }
}

PassHolder/Controllers/PassDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using AutoMapper;
using PassHolder.Commands;
using PassHolder.Entities;
using PassHolder.Models;
using MediatR;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using PassHolder.Queries;
using PassHolder.ViewModel;
using Microsoft.AspNetCore.Antiforgery;

namespace PassHolder.Controllers
{
    public class PassDataController : Controller
    {
        private UserManager<AppUser> _userManager;
        private SignInManager<AppUser> _singInManager;
        private RoleManager<AppRole> _roleManager;
        private readonly IMapper _mapper;
        private readonly IMediator _mediator;

        public PassDataController(UserManager<AppUser> userManager, 
           SignInManager<AppUser> singInManager,
           RoleManager<AppRole> roleManager,
           IMapper mapper,
           IMediator mediator)
        {
            _userManager = userManager;
            _singInManager = singInManager;
            _roleManager = roleManager;
            _mapper = mapper;
            _mediator = mediator;
        }


        public async Task<IActionResult> PassDataLoad()
        {

            ViewBag.Title = "PassData";
            var passData = await _mediator.Send(new AllPassDataQuery());

            var passDataVM = new PassDataViewModel() { PassDatas = passData };
            passDataVM.SelectedPassData = null;

            return View("PassData", passDataVM);
        }

        [HttpPost]
        public async Task<IActionResult> New()
        {

            ViewBag.Title = "PassData";
            var passData = await _mediator.Send(new AllPassDataQuery());

            var passDataVM = new PassDataViewModel() { PassDatas = passData };
            passDataVM.SelectedPassData = null;
            passDataVM.DisplayMode = "WriteOnly";

            return View("PassData", passDataVM);
        }

        [HttpPost]
        public async Task<IActionResult> Insert(PassDataModel newPassData)
        {

            var passData = await _mediator.Send(new AddPassDataCommand() 
            { 
                Login = newPassData.Login,
                Name = newPassData.Name,
                Password = newPassData.Password,
                Description = newPassData.Description
            });

            var passDatas = await _mediator.Send(new AllPassDataQuery());

            var model = new PassDataViewModel() { PassDatas = passDatas };

            model.SelectedPassData = passData;
            model.DisplayMode = "";

            return View("PassData", model);
        }

        [HttpPost]
        public async Task<IActionResult> Select(string id)
        {
            PassDataViewModel model = new PassDataViewModel();

            model.PassDatas = await _mediator.Send(new AllPassDataQuery());
            model.SelectedPassData = await _mediator.Send(new PassDataQuery() { Id = int.Parse(id) });
            model.DisplayMode = "ReadOnly";

            return View("PassData", model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id)
        {
            PassDataViewModel model = new PassDataViewModel();

            model.PassDatas = await _mediator.Send(new AllPassDataQuery());
            model.SelectedPassData = await _mediator.Send(new PassDataQuery() { Id = int.Parse(id) });
            model.DisplayMode = "ReadWrite";

            return View("PassData", model);
            
        }

        [HttpPost]
        public async Task<IActionResult> Update(PassDataModel obj)
        {

            var passData = await _mediator.Send(new UpdatePassDataCommand()
            {
                Id = obj.Id,
                Login = obj.Login,
                Name = obj.Name,
                Password = obj.Password,
                Description = obj.Description
            });

            PassDataViewModel model = new PassDataViewModel();

            model.PassDatas = await _mediator.Send(new AllPassDataQuery());

            model.SelectedPassData = passData;
            model.DisplayMode = "";

            return View("PassData", model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {

            await _mediator.Publish(new DeletePassDataCommand() { Id = int.Parse(id) });
            
            PassDataViewModel model = new PassDataViewModel();

            model.PassDatas = await _mediator.Send(new AllPassDataQuery());

            model.SelectedPassData = null;
            model.DisplayMode = "";

            return View("PassData", model);
        }

        [HttpPost]
        public async Task<IActionResult> Cancel(string id)
        {
            _mediator.Publish(new DeletePassDataCommand() { Id = int.Parse(id) });

            PassDataViewModel model = new PassDataViewModel();

            model.PassDatas = await _mediator.Send(new AllPassDataQuery());

            model.SelectedPassData = model.SelectedPassData = await _mediator.Send(new PassDataQuery() { Id = int.Parse(id) });
            model.DisplayMode = "";

            return View("PassData", model);
        }

    }
}

PassHolder/Pages/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PassHolder.Pages
{
    public class LoginModel : PageModel
    {
        private readonly ILogger<LoginModel> _logger;

        public LoginModel(ILogger<LoginModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PassHolder/Pages/Shared/Groups.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PassHolder.Pages.Shared
{
    public class GroupsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PassHolder/Pages/Shared/PassData.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace PassHolder.Pages.Shared
{
    public class PassDataModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

PassHolder/Pages/Shared/Registration.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PassHolder.Pages.Shared
{
    public class RegistrationModel : PageModel
    {
        private readonly ILogger<RegistrationModel> _logger;

        public RegistrationModel(ILogger<RegistrationModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PassHolder/Pages/Shared/Groups.cshtml
@model List<Models.GroupModel>

<h3>@ViewBag.Title</h3>

@foreach (var group in Model)
{
    <div>
        <label for="group">@group.Id </label> <label for="group">@group.Name </label><br />
    </div>

    <label for="group">UsersToGroup: </label>
    <br />
    foreach (var user in group.users)
    {
<div>
    <label for="user">@user.Id, </label> <label for="user">@user.UserName, </label><br /> <label for="user">@user.IsAdmin, </label><br />
</div>

    }

}

PassHolder/Pages/Shared/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<h2>Login</h2>
<div>
    @ViewBag.Result
</div>

PassHolder/Pages/Shared/PassData.cshtml
@model PassHolder.ViewModel.PassDataViewModel

    <h1>List of Customers</h1>

    <form method="post">
        <input type="submit" value="Insert" formaction="new" />
        <br /><br />
        <table border="1" cellpadding="10">
            <tr>
                <th>PassData ID</th>
                <th>PassData Name</th>
                <th colspan="2">Actions</th>
            </tr>
            @foreach (var item in Model.PassDatas)
            {
                if (Model.SelectedPassData != null)
                {
                    if (item.Id == Model.SelectedPassData.Id)
                    {
                        @:<tr class="SelectedCustomer">
                    }
                    else
                    {
                        @: <tr>
                    }
                }
                else
                {
                    @: <tr>
                }
                    <td>@item.Id</td>
                    <td>@item.Name</td>
                    <td>
                        <input type="submit" value="Edit" formaction="select/@item.Id" />
                    </td>
                    <td>
                        <input type="submit" value="Delete" formaction="delete/@item.Id"/>
                    </td>
                @:</tr>
            }
        </table>
    </form>
    <br /><br />
    @{
        if (Model.SelectedPassData != null)
        {
            if (Model.DisplayMode == "ReadOnly")
            {
                await Html.RenderPartialAsync("PassData/ShowPassData", Model.SelectedPassData);
            }
            if (Model.DisplayMode == "ReadWrite")
            {
                await Html.RenderPartialAsync("PassData/EditPassData", Model.SelectedPassData);
            }
        }
        if (Model.DisplayMode == "WriteOnly")
        {
            await Html.RenderPartialAsync("PassData/_InsertPassData", new PassHolder.Models.PassDataModel());
        }
    }
    }

PassHolder/Pages/Shared/Register.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Register";
}

<h2>Register</h2>
<p>@ViewBag.Message</p>
<div>
    <a asp-controller="Account" asp-action="Login">Login</a>
</div>

PassHolder/Pages/Shared/Registration.cshtml
@model Models.RegisterUserModel

<h3>@ViewBag.Title</h3>

<form asp-action="Register" asp-controller="Account" method="post" role="form">
    <div>
        <div>
            <label asp-for="Email"></label><br />
        </div>

        <div>
            <input asp-for="Email" type="email" />
            <span asp-validation-for="Email"></span>
        </div>
    </div>

    <div>
        <div>
            <label asp-for="UserName"></label><br />
        </div>

        <div>
            <input asp-for="UserName" type="text" />
            <span asp-validation-for="UserName"></span>
        </div>
    </div>

    <div>
        <div>
            <label asp-for="FirstName"></label><br />
        </div>

        <div>
            <input asp-for="FirstName" type="text" />
            <span asp-validation-for="FirstName"></span>
        </div>
    </div>

    <div>
        <div>
            <label asp-for="LastName"></label><br />
        </div>

        <div>
            <input asp-for="LastName" type="text" />
            <span asp-validation-for="LastName"></span>
        </div>
    </div>

    <div>
        <div>
            <label asp-for="Password"></label><br />
        </div>

        <div>
            <input asp-for="Password" type="password" />
            <span asp-validation-for="Password"></span>
        </div>
    </div>
    <div>
        <div>
            <label asp-for="RoleId"></label><br />
        </div>

        <div>
        <select asp-for="RoleId" asp-items="@Model.Roles
            .Select(r => new SelectListItem() {Text = r.Name, Value = r.Id.ToString() })"></select>
    </div>
    </div>
  
    <div>
        <br />
        <input type="submit" value="Rejestracja" />
    </div>
</form>

PassHolder/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PassHolder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">PassHolder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Account" asp-action="RegisterLoad">Sing up</a>
                        </li>
                        <li>
                            @if (User.Identity.IsAuthenticated)
                            {
                                <a class="nav-link text-dark" asp-controller="Account" asp-action="Logout">@User.Identity.Name, Logout</a>
                            }
                            else
                            {
                                <a class="nav-link text-dark" asp-area="" asp-page="/Login">Sing in</a>
                            }
                        </li>     
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Group" asp-action="GroupsLoad">Groups</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li> <a class="nav-link text-dark" asp-controller="PassData" asp-action="PassDataLoad">PassData</a> </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PassHolder - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>